# Generated by Django 4.0.5 on 2023-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, upload_to='books/'),
        ),
    ]
