# Generated by Django 4.0.5 on 2023-05-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
